let shopItemsData = [
  {
    id: "milk001",
    name: "Sữa Tươi TH true 1L",
    price: 35000,
    desc: "Sữa tươi tiệt trùng nguyên chất, bổ sung canxi và vitamin D.",
    img: "img/SuaTH.png",
  },
  {
    id: "milk002",
    name: "Sữa TH true 380g",
    price: 28000,
    desc: "Sữa đặc có đường, hương vị truyền thống, dùng pha chế.",
    img: "img/SuaTH1.png",
  },
  {
    id: "milk003",
    name: "Sữa TH true 180ml",
    price: 40000,
    desc: "Sữa ca cao lúa mạch cung cấp năng lượng cho trẻ em.",
    img: "img/SuaTH2.png",
  },
  {
    id: "milk004",
    name: "Sữa TH true 200ml",
    price: 40000,
    desc: "Sữa đậu nành tự nhiên, tốt cho tim mạch và sức khỏe.",
    img: "img/SuaTH3.png",
  },
  {
    id: "milk005",
    name: "Sữa TH true 850g",
    price: 45000,
    desc: "Sữa dinh dưỡng cao cấp cho người lớn tuổi và người bệnh.",
    img: "img/SuaTH4.png",
  },
  {
    id: "milk006",
    name: "Sữa TH true 900g",
    price: 32000,
    desc: "Sữa bột giúp phát triển chiều cao và trí não cho trẻ.",
    img: "img/SuaTH5.png",
  },
  {
    id: "milk007",
    name: "Sữa TH true IQ 900g",
    price: 29000,
    desc: "Sữa bột giàu DHA, hỗ trợ phát triển trí tuệ cho bé.",
    img: "img/SuaTH6.png",
  },
  {
    id: "milk008",
    name: "Sữa TH true Organic 1L",
    price: 40000,
    desc: "Sữa tươi hữu cơ, không hóa chất, an toàn cho sức khỏe.",
    img: "img/SuaTH10.png",
  },
  {
    id: "milk009",
    name: "Sữa TH True Milk 1L",
    price: 38000,
    desc: "Sữa tươi sạch từ trang trại TH, vị thơm ngon tự nhiên.",
    img: "img/SuaTH8.png",
  },
  {
    id: "milk010",
    name: "Sữa TH true 850g",
    price: 42000,
    desc: "Sữa bột cao cấp, bổ sung DHA, hỗ trợ tiêu hóa cho trẻ.",
    img: "img/SuaTH9.png",
  },
];
