let shopItemsData = [
  {
    id: "milk001",
    name: "Sữa Tươi Vinamilk 1L",
    price: 35,
    desc: "Sữa tươi tiệt trùng nguyên chất, bổ sung canxi và vitamin D.",
    img: "img/SuaTH.png",
  },
  {
    id: "milk002",
    name: "Sữa Ông Thọ 380g",
    price: 28,
    desc: "Sữa đặc có đường, hương vị truyền thống, dùng pha chế.",
    img: "img/SuaTH1.png",
  },
  {
    id: "milk003",
    name: "Sữa Milo 180ml",
    price: 12,
    desc: "Sữa ca cao lúa mạch cung cấp năng lượng cho trẻ em.",
    img: "img/SuaTH2.png",
  },
  {
    id: "milk004",
    name: "Sữa Đậu Nành Fami 200ml",
    price: 10,
    desc: "Sữa đậu nành tự nhiên, tốt cho tim mạch và sức khỏe.",
    img: "img/SuaTH3.png",
  },
  {
    id: "milk005",
    name: "Sữa Ensure Gold 850g",
    price: 450,
    desc: "Sữa dinh dưỡng cao cấp cho người lớn tuổi và người bệnh.",
    img: "img/SuaTH4.png",
  },
  {
    id: "milk006",
    name: "Sữa Abbott Grow 900g",
    price: 320,
    desc: "Sữa bột giúp phát triển chiều cao và trí não cho trẻ.",
    img: "img/SuaTH5.png",
  },
  {
    id: "milk007",
    name: "Sữa Nutifood Nuti IQ 900g",
    price: 295,
    desc: "Sữa bột giàu DHA, hỗ trợ phát triển trí tuệ cho bé.",
    img: "img/SuaTH6.png",
  },
  {
    id: "milk008",
    name: "Sữa Vinamilk Organic 1L",
    price: 40,
    desc: "Sữa tươi hữu cơ, không hóa chất, an toàn cho sức khỏe.",
    img: "img/SuaTH10.png",
  },
  {
    id: "milk009",
    name: "Sữa TH True Milk 1L",
    price: 38,
    desc: "Sữa tươi sạch từ trang trại TH, vị thơm ngon tự nhiên.",
    img: "img/SuaTH8.png",
  },
  {
    id: "milk010",
    name: "Sữa Friso Gold 850g",
    price: 420,
    desc: "Sữa bột cao cấp, bổ sung DHA, hỗ trợ tiêu hóa cho trẻ.",
    img: "img/SuaTH9.png",
  },
];
